name: NodeJS with Webpack

on:
  push:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      run: npm install

    - name: Build Angular App
      run: npm run build

    - name: Configure Git User
      run: |
        git config --global user.email "dominiktb2@gmail.com"
        git config --global user.name "Domepo"

    - name: Deploy to GH pages
      run: |
        npx angular-cli-ghpages --dir=dist/lernduell/browser --no-silent
      env:
        CI: true
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
