name: NodeJS with Webpack

on:
  push:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      run: npm install

    - name: Build Angular App
      run: npm run build
            
    - name: Create file in ./dist/lernduell
      run: touch ./dist/lernduell/test.md

    - name: Verify Build Output
      run: ls -la ./dist/lernduell

    - name: Copy
      run: cp /home/runner/work/lernduell/lernduell/dist/lernduell /home/runner/actions_github_pages_1734517644174

    - name: test
      run: ls /home/runner/actions_github_pages_1734517644174
      
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist/lernduell
        enable_jekyll: false
